const origin='http://localhost:5173';
const auth=await fetch(origin+'/signin-with-chatgpt?return_to=/',{redirect:'manual'});
const cookie=auth.headers.getSetCookie().map(s=>s.split(';')[0]).join('; ');
const headers={'Cookie':cookie,'Origin':origin,'Content-Type':'application/json'};
const get=async()=>{const r=await fetch(origin+'/api/fleet',{headers});if(!r.ok)throw Error(await r.text());return r.json()};
const first=await get();console.log('Authenticated read',first.vehicles.length);
const {blankVehicle}=await import('../lib/fleet.ts');
const v={...blankVehicle,registration:'QA-API-'+Date.now(),roadworthy:'2026-09-20',insurance:'2027-09-20'};
const save=async(data)=>fetch(origin+'/api/fleet',{method:'POST',headers,body:JSON.stringify(data)});
const added=await save(v);if(added.status!==200)throw Error(await added.text());const record=(await get()).vehicles.find(x=>x.registration===v.registration);if(!record)throw Error('Not persisted');
const duplicate=await save(v);if(duplicate.status!==409)throw Error('Duplicate not blocked');
const renewed=await save({...record,roadworthy:'2027-09-20'});if(renewed.status!==200)throw Error(await renewed.text());
const stale=await save({...record,notes:'stale'});if(stale.status!==409)throw Error('Stale update not blocked');
const current=(await get()).vehicles.find(x=>x.id===record.id);const archive=await save({...current,archived:1});if(archive.status!==200)throw Error(await archive.text());
const final=await get();if(!final.activity.some(x=>x.vehicleId===record.id&&x.action==='Vehicle archived'))throw Error('Audit missing');
const anonymous=await fetch(origin+'/api/fleet');if(anonymous.status!==401)throw Error('Anonymous allowed');
const invalid=await save({...v,registration:'QA-INVALID',roadworthy:'2026-02-30'});if(invalid.status!==400)throw Error('Invalid date allowed');
console.log('Passed: create/read, duplicate protection, renewal, stale-update protection, archive/audit, anonymous rejection, invalid-date validation.');
