export const categories = ['Light Vehicles (LVs)', 'Dump trucks (DTs)', 'Articulator dump trucks (ADs)', 'Service Trucks', 'Lowbeds'] as const;
export type Vehicle = {id:string; registration:string; asset:string; category:string; model:string; site:string; responsible:string; roadworthy:string; roadworthyNumber:string; insurance:string; policyNumber:string; insurer:string; notes:string; archived:number; revision:number};
export type Activity = {id:string; vehicleId:string; registration:string; action:string; detail:string; actor:string; createdAt:string};
export const blankVehicle:Vehicle={id:'',registration:'',asset:'',category:categories[0],model:'',site:'',responsible:'',roadworthy:'',roadworthyNumber:'',insurance:'',policyNumber:'',insurer:'',notes:'',archived:0,revision:0};
export function today(){return new Date().toISOString().slice(0,10)}
export function days(date:string, reference=today()){return date ? Math.round((Date.parse(date+'T00:00:00Z')-Date.parse(reference+'T00:00:00Z'))/86400000) : null}
export function documentStatus(date:string, reference=today()){const d=days(date,reference); return d===null?'Missing':d<0?'Expired':d<=30?'Due soon':'Valid'}
export function vehicleStatus(v:Vehicle, reference=today()){const statuses=[documentStatus(v.roadworthy,reference),documentStatus(v.insurance,reference)];return statuses.includes('Expired')?'Expired':statuses.includes('Missing')?'Missing':statuses.includes('Due soon')?'Due soon':'Valid'}
export function dateLabel(date:string){return date ? new Date(date+'T00:00:00Z').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric',timeZone:'UTC'}):'Not recorded'}
export function sampleVehicles():Vehicle[]{const date=(n:number)=>new Date(Date.parse(today()+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);return categories.flatMap((category,i)=>[0,1].map(j=>({...blankVehicle,id:`sample-${i}-${j}`,registration:`DEMO ${100+i*10+j}`,asset:`${['LV','DT','AD','ST','LB'][i]}-${String(j+1).padStart(3,'0')}`,category,model:['Toyota Hilux','Shacman F3000','Volvo A40G','Isuzu FVR','MAN TGX'][i],site:j?'Tarkwa':'Head office',responsible:'Sample fleet officer',roadworthy:date([90,14,-8,180,42][i]+j*20),insurance:i===3&&j===0?'':date([150,60,21,90,-3][i]+j*30),insurer:'Sample insurer'})))}
export function csvCell(value:unknown){let s=String(value??'');if(/^[\s]*[=+@-]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"'}
