import {database} from '@/lib/database';
import {hasStaffSession} from '@/lib/staff-auth';
import {categories, blankVehicle, type Vehicle} from '@/lib/fleet';
export const dynamic='force-dynamic';
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(request:Request){try{if(!await hasStaffSession(request))return json({error:'Sign in to access your fleet.'},401);const db=database();const [v,a]=await db.batch([db.prepare('SELECT * FROM vehicles ORDER BY registration'),db.prepare('SELECT * FROM activity ORDER BY createdAt DESC LIMIT 200')]);return json({vehicles:v.results,activity:a.results})}catch(e){console.error('Fleet load',e);return json({error:'Unable to load fleet records. Please retry.'},503)}}
export async function POST(request:Request){try{if(!await hasStaffSession(request))return json({error:'Sign in before saving.'},401);if(request.headers.get('origin')!==new URL(request.url).origin)return json({error:'Invalid request origin.'},403);const body=await request.json() as Record<string,unknown>;if(!body||typeof body!=="object"||Array.isArray(body))return json({error:"Invalid vehicle record."},400);const v:Vehicle={...blankVehicle};for(const key of Object.keys(blankVehicle)){if(['archived','revision'].includes(key))continue;const value=body[key];if(typeof value!=='string'||value.length>(key==='notes'?2000:160))return json({error:`Invalid ${key}.`},400);(v as unknown as Record<string,unknown>)[key]=value.trim()}
v.registration=v.registration.toUpperCase().replace(/\s+/g,' ');v.archived=body.archived===1?1:0;v.revision=Number(body.revision);if(!v.registration||!categories.includes(v.category as typeof categories[number])||!Number.isInteger(v.revision)||v.revision<0)return json({error:'Registration and a valid vehicle category are required.'},400);
for(const field of ['roadworthy','insurance'] as const){const value=v[field];if(value&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||Number.isNaN(Date.parse(value))||new Date(value).toISOString().slice(0,10)!==value))return json({error:'Enter valid expiry dates.'},400)}
const db=database();const previous=v.id?await db.prepare('SELECT * FROM vehicles WHERE id=?').bind(v.id).first<Vehicle>():null;if(v.id&&!previous)return json({error:'Vehicle no longer exists. Refresh the register.'},404);if(previous&&previous.revision!==v.revision)return json({error:'This vehicle was updated elsewhere. Close this form and refresh before editing.'},409);const id=previous?.id||crypto.randomUUID();const keys=Object.keys(blankVehicle).filter(k=>!['id','revision'].includes(k));const values=keys.map(k=>(v as unknown as Record<string,unknown>)[k]);const action=!previous?'Vehicle added':previous.archived!==v.archived?(v.archived?'Vehicle archived':'Vehicle restored'):'Vehicle updated';const changes=previous?keys.filter(k=>String(previous[k as keyof Vehicle])!==String(v[k as keyof Vehicle])).map(k=>`${k}: ${previous[k as keyof Vehicle]||'not recorded'} → ${v[k as keyof Vehicle]||'not recorded'}`).join('; '):`${v.category} · ${v.registration}`;
if(previous&&!changes)return json({ok:true});const mutation=previous?db.prepare(`UPDATE vehicles SET ${keys.map(k=>`"${k}"=?`).join(',')},revision=revision+1 WHERE id=? AND revision=?`).bind(...values,id,v.revision):db.prepare(`INSERT INTO vehicles (id,${keys.map(k=>`"${k}"`).join(',')},revision) VALUES (?,${keys.map(()=>'?').join(',')},1)`).bind(id,...values);
const audit=db.prepare('INSERT INTO activity (id,vehicleId,registration,action,detail,actor,createdAt) SELECT ?,?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),id,v.registration,action,changes,'Staff access',new Date().toISOString());const result=await db.batch([mutation,audit]);if(result[0].meta.changes!==1)return json({error:'Another user changed this record. Refresh and try again.'},409);return json({ok:true,id})}catch(e){console.error('Fleet save',e);if(String(e).includes('UNIQUE'))return json({error:'A vehicle with this registration already exists, including archived records.'},409);return json({error:'Unable to save. Your entries have been kept; please try again.'},503)}}

